using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendBiblioMate.Models
{
    /// <summary>
    /// Represents an author of a book in the system.
    /// Contains primary identification and navigation to related books.
    /// </summary>
    public class Author
    {
        /// <summary>
        /// Gets or sets the unique identifier of the author.
        /// </summary>
        /// <remarks>
        /// This value is generated by the database as an identity column.
        /// </remarks>
        /// <example>1</example>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AuthorId { get; init; }

        /// <summary>
        /// Gets or sets the full name of the author.
        /// </summary>
        /// <remarks>
        /// Must be between 2 and 100 characters.
        /// </remarks>
        /// <example>J.K. Rowling</example>
        [Required(ErrorMessage = "Author name is required.")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Author name must be between 2 and 100 characters.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets the collection of books written by this author.
        /// </summary>
        /// <remarks>
        /// Navigation property used by Entity Framework Core for relationships.
        /// Initialized to an empty list by default.
        /// </remarks>
        public ICollection<Book> Books { get; init; } = new List<Book>();
    }
}