using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendBiblioMate.Models
{
    /// <summary>
    /// Represents a publisher or editor of books within the system.
    /// Contains identification details and navigation to associated books.
    /// </summary>
    public class Editor
    {
        /// <summary>
        /// Gets or sets the unique identifier of the editor.
        /// </summary>
        /// <remarks>
        /// This value is generated by the database as an identity column.
        /// </remarks>
        /// <example>3</example>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EditorId { get; init; }

        /// <summary>
        /// Gets or sets the name of the editor or publishing house.
        /// </summary>
        /// <remarks>
        /// Must be between 2 and 100 characters.
        /// </remarks>
        /// <example>Penguin Random House</example>
        [Required(ErrorMessage = "Editor name is required.")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Editor name must be between 2 and 100 characters.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets the collection of books published by this editor.
        /// </summary>
        /// <remarks>
        /// Navigation property used by Entity Framework Core for relationships.
        /// Initialized to an empty list by default.
        /// </remarks>
        public ICollection<Book> Books { get; init; } = new List<Book>();
    }
}