using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendBiblioMate.Models
{
    /// <summary>
    /// Records a user-centric event (loan, return, reservation, cancellation, etc.)
    /// for audit and history purposes.
    /// </summary>
    public class History
    {
        /// <summary>
        /// Gets or sets the unique identifier of the history record.
        /// </summary>
        /// <remarks>
        /// This value is generated by the database as an identity column.
        /// </remarks>
        /// <example>123</example>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int HistoryId { get; init; }

        /// <summary>
        /// Gets or sets the identifier of the user associated with this event.
        /// </summary>
        /// <example>7</example>
        [Required(ErrorMessage = "UserId is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "UserId must be a positive integer.")]
        public int UserId { get; init; }

        /// <summary>
        /// Gets or sets the optional identifier of the related loan, if applicable.
        /// </summary>
        /// <example>45</example>
        [Range(1, int.MaxValue, ErrorMessage = "LoanId must be a positive integer.")]
        public int? LoanId { get; init; }

        /// <summary>
        /// Gets or sets the optional identifier of the related reservation, if applicable.
        /// </summary>
        /// <example>78</example>
        [Range(1, int.MaxValue, ErrorMessage = "ReservationId must be a positive integer.")]
        public int? ReservationId { get; init; }

        /// <summary>
        /// Gets or sets the exact date and time when the event occurred (UTC).
        /// </summary>
        /// <example>2025-06-23T14:30:00Z</example>
        [Required(ErrorMessage = "EventDate is required.")]
        public DateTime EventDate { get; init; }

        /// <summary>
        /// Gets or sets the type of event.
        /// </summary>
        /// <remarks>
        /// Possible values include: "Loan", "Return", "Reservation", "Cancel".
        /// </remarks>
        /// <example>Loan</example>
        [Required(ErrorMessage = "EventType is required.")]
        [StringLength(50, ErrorMessage = "EventType cannot exceed 50 characters.")]
        public string EventType { get; init; } = string.Empty;

        /// <summary>
        /// Gets or sets the navigation property to the user who triggered the event.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public User User { get; init; } = null!;

        /// <summary>
        /// Gets or sets the navigation property to the related loan, if applicable.
        /// </summary>
        [ForeignKey(nameof(LoanId))]
        public Loan? Loan { get; init; }

        /// <summary>
        /// Gets or sets the navigation property to the related reservation, if applicable.
        /// </summary>
        [ForeignKey(nameof(ReservationId))]
        public Reservation? Reservation { get; init; }
    }
}
