using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendBiblioMate.Models
{
    /// <summary>
    /// Represents an application user with authentication, profile data, and related records.
    /// </summary>
    public class User
    {
        /// <summary>
        /// Gets the primary key of the user.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get; init; }

        /// <summary>
        /// Gets or sets the full name of the user.
        /// </summary>
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Name must be between 2 and 100 characters.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the email address, used for login and notifications.
        /// </summary>
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Email must be a valid email address.")]
        [StringLength(100, ErrorMessage = "Email cannot exceed 100 characters.")]
        public string Email { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the hashed password for authentication.
        /// </summary>
        [Required(ErrorMessage = "Password is required.")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be between 6 and 100 characters.")]
        public string Password { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the postal address of the user.
        /// </summary>
        [Required(ErrorMessage = "Address is required.")]
        [StringLength(200, ErrorMessage = "Address cannot exceed 200 characters.")]
        public string Address { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the phone number of the user.
        /// </summary>
        [Required(ErrorMessage = "Phone is required.")]
        [Phone(ErrorMessage = "Phone must be a valid phone number.")]
        public string Phone { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the role of the user (User, Librarian, Admin).
        /// </summary>
        [Required(ErrorMessage = "Role is required.")]
        [RegularExpression(@"^(User|Librarian|Admin)$", ErrorMessage = "Role must be 'User', 'Librarian', or 'Admin'.")]
        [StringLength(20, ErrorMessage = "Role cannot exceed 20 characters.")]
        public string Role { get; set; } = "User";

        /// <summary>
        /// Gets a value indicating whether the user's email address has been confirmed.
        /// </summary>
        public bool IsEmailConfirmed { get; set; } = false;

        /// <summary>
        /// Gets or sets the token sent to confirm the user's email, if pending.
        /// </summary>
        [StringLength(1000, ErrorMessage = "EmailConfirmationToken cannot exceed 1000 characters.")]
        public string? EmailConfirmationToken { get; set; }

        /// <summary>
        /// Gets or sets the token sent to reset the user's password, if requested.
        /// </summary>
        [StringLength(1000, ErrorMessage = "PasswordResetToken cannot exceed 1000 characters.")]
        public string? PasswordResetToken { get; set; }

        /// <summary>
        /// Gets or sets the expiration date and time for the password reset token.
        /// </summary>
        public DateTime? PasswordResetTokenExpires { get; set; }

        /// <summary>
        /// Gets a value indicating whether the user account has been approved by an administrator.
        /// </summary>
        public bool IsApproved { get; set; } = false;

        /// <summary>
        /// Gets the collection of loan records associated with the user.
        /// </summary>
        public ICollection<Loan> Loans { get; init; } = new List<Loan>();

        /// <summary>
        /// Gets the collection of reservation records associated with the user.
        /// </summary>
        public ICollection<Reservation> Reservations { get; init; } = new List<Reservation>();

        /// <summary>
        /// Gets the collection of reports generated by the user.
        /// </summary>
        public ICollection<Report> Reports { get; init; } = new List<Report>();

        /// <summary>
        /// Gets the collection of recommendations generated for the user.
        /// </summary>
        public ICollection<Recommendation> Recommendations { get; init; } = new List<Recommendation>();

        /// <summary>
        /// Gets the collection of notifications sent to the user.
        /// </summary>
        public ICollection<Notification> Notifications { get; init; } = new List<Notification>();

        /// <summary>
        /// Gets the preferred genres of the user for personalized recommendations.
        /// </summary>
        public ICollection<UserGenre> UserGenres { get; init; } = new List<UserGenre>();

        /// <summary>
        /// Gets or sets the security stamp used to invalidate existing tokens on critical changes.
        /// </summary>
        [Required(ErrorMessage = "SecurityStamp is required.")]
        [StringLength(1000, ErrorMessage = "SecurityStamp cannot exceed 1000 characters.")]
        public string SecurityStamp { get; set; } = Guid.NewGuid().ToString();
    }
}