services:
  serverSQL:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlservercda
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234!
    ports:
      - "1450:1433"
    volumes:
      - sqlDB_data:/var/opt/mssql
  
  app:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: app
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - serverSQL
    tty: true
volumes:
  sqlDB_data:
    