using System.Text;
using Microsoft.EntityFrameworkCore;
using BackendBiblioMate.Data;
using BackendBiblioMate.DTOs;
using BackendBiblioMate.Interfaces;
using BackendBiblioMate.Models;

namespace BackendBiblioMate.Services.Reports
{
    /// <summary>
    /// Provides CRUD operations and analytical report generation for user activity.
    /// Uses EF Core for data access and computes basic loan statistics.
    /// </summary>
    public class ReportService : IReportService
    {
        private readonly BiblioMateDbContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReportService"/> class.
        /// </summary>
        /// <param name="context">The EF Core database context.</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="context"/> is <c>null</c>.</exception>
        public ReportService(BiblioMateDbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <summary>
        /// Retrieves all reports in the system, ordered by generation date (most recent first).
        /// </summary>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns>List of <see cref="ReportReadDto"/>.</returns>
        public async Task<List<ReportReadDto>> GetAllAsync(
            CancellationToken cancellationToken = default)
        {
            var reports = await _context.Reports
                .AsNoTracking()
                .Include(r => r.User)
                .OrderByDescending(r => r.GeneratedDate)
                .ToListAsync(cancellationToken);

            return reports.Select(ToDto).ToList();
        }

        /// <summary>
        /// Retrieves all reports generated by a specific user, ordered by generation date (most recent first).
        /// </summary>
        /// <param name="userId">The identifier of the user.</param>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns>List of <see cref="ReportReadDto"/>.</returns>
        public async Task<List<ReportReadDto>> GetAllForUserAsync(
            int userId,
            CancellationToken cancellationToken = default)
        {
            var reports = await _context.Reports
                .AsNoTracking()
                .Where(r => r.UserId == userId)
                .Include(r => r.User)
                .OrderByDescending(r => r.GeneratedDate)
                .ToListAsync(cancellationToken);

            return reports.Select(ToDto).ToList();
        }

        /// <summary>
        /// Retrieves a single report by its identifier.
        /// </summary>
        /// <param name="reportId">The identifier of the report.</param>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns>
        /// The <see cref="ReportReadDto"/> if found; otherwise <c>null</c>.
        /// </returns>
        public async Task<ReportReadDto?> GetByIdAsync(
            int reportId,
            CancellationToken cancellationToken = default)
        {
            var report = await _context.Reports
                .AsNoTracking()
                .Include(r => r.User)
                .FirstOrDefaultAsync(r => r.ReportId == reportId, cancellationToken);

            return report == null ? null : ToDto(report);
        }

        /// <summary>
        /// Generates a new monthly report with statistics such as loan counts and top books.
        /// Saves the report to the database and returns the result as a DTO.
        /// </summary>
        /// <param name="dto">The creation parameters containing the report title.</param>
        /// <param name="userId">The identifier of the user creating the report.</param>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns>The created <see cref="ReportReadDto"/>.</returns>
        public async Task<ReportReadDto> CreateAsync(
            ReportCreateDto dto,
            int userId,
            CancellationToken cancellationToken = default)
        {
            var now = DateTime.UtcNow;
            var thisMonthStart = new DateTime(now.Year, now.Month, 1);
            var lastMonthStart = thisMonthStart.AddMonths(-1);

            // Count loans for this month and last month
            var totalThisMonth = await _context.Loans
                .AsNoTracking()
                .CountAsync(l => l.LoanDate >= thisMonthStart, cancellationToken);

            var totalLastMonth = await _context.Loans
                .AsNoTracking()
                .CountAsync(l => l.LoanDate >= lastMonthStart && l.LoanDate < thisMonthStart, cancellationToken);

            // Calculate percentage change between months
            var pctChange = totalLastMonth == 0
                ? 100
                : (int)Math.Round((totalThisMonth - (double)totalLastMonth) / totalLastMonth * 100);

            // Get top 3 most loaned books for this month
            var topBooks = await _context.Loans
                .AsNoTracking()
                .Where(l => l.LoanDate >= thisMonthStart)
                .GroupBy(l => l.BookId)
                .Select(g => new { BookId = g.Key, Count = g.Count() })
                .OrderByDescending(g => g.Count)
                .Take(3)
                .Join(_context.Books.AsNoTracking(),
                      g => g.BookId,
                      b => b.BookId,
                      (g, b) => new { b.Title, g.Count })
                .ToListAsync(cancellationToken);

            // Build the report content
            var sb = new StringBuilder();
            sb.AppendLine($"Loans this month: {totalThisMonth}");
            sb.AppendLine($"Loans last month: {totalLastMonth} ({pctChange:+0;-0}% change)");
            sb.AppendLine("Top 3 books this month:");
            foreach (var tb in topBooks)
                sb.AppendLine($" - {tb.Title} ({tb.Count} loans)");

            // Persist the report
            var report = new Report
            {
                Title         = dto.Title,
                Content       = sb.ToString().TrimEnd(),
                UserId        = userId,
                GeneratedDate = now
            };

            _context.Reports.Add(report);
            await _context.SaveChangesAsync(cancellationToken);

            // Reload navigation property for user
            await _context.Entry(report)
                          .Reference(r => r.User)
                          .LoadAsync(cancellationToken);

            return ToDto(report);
        }

        /// <summary>
        /// Updates an existing report’s title and content.
        /// </summary>
        /// <param name="dto">The update parameters containing new title and content.</param>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns><c>true</c> if updated; <c>false</c> if not found.</returns>
        public async Task<bool> UpdateAsync(
            ReportUpdateDto dto,
            CancellationToken cancellationToken = default)
        {
            var report = await _context.Reports
                .FindAsync(new object[] { dto.ReportId }, cancellationToken);

            if (report == null)
                return false;

            report.Title   = dto.Title;
            report.Content = dto.Content;

            await _context.SaveChangesAsync(cancellationToken);
            return true;
        }

        /// <summary>
        /// Deletes a report by its identifier.
        /// </summary>
        /// <param name="reportId">The identifier of the report to delete.</param>
        /// <param name="cancellationToken">Token to observe for cancellation requests.</param>
        /// <returns><c>true</c> if deleted; <c>false</c> if not found.</returns>
        public async Task<bool> DeleteAsync(
            int reportId,
            CancellationToken cancellationToken = default)
        {
            var report = await _context.Reports
                .FindAsync(new object[] { reportId }, cancellationToken);

            if (report == null)
                return false;

            _context.Reports.Remove(report);
            await _context.SaveChangesAsync(cancellationToken);
            return true;
        }

        /// <summary>
        /// Maps a <see cref="Report"/> entity to a <see cref="ReportReadDto"/>.
        /// </summary>
        /// <param name="r">The entity to map.</param>
        /// <returns>A corresponding <see cref="ReportReadDto"/>.</returns>
        private static ReportReadDto ToDto(Report r) => new()
        {
            ReportId      = r.ReportId,
            UserId        = r.UserId,
            UserName      = r.User != null ? $"{r.User.FirstName} {r.User.LastName}".Trim() : string.Empty,
            Title         = r.Title,
            Content       = r.Content,
            GeneratedDate = r.GeneratedDate
        };
    }
}
