using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace backend.Models
{
    /// <summary>
    /// Represents a report generated by a user, containing analytics or statistics.
    /// </summary>
    public class Report
    {
        /// <summary>
        /// Primary key of the report.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ReportId { get; set; }

        /// <summary>
        /// Identifier of the user who generated the report.
        /// </summary>
        [Required(ErrorMessage = "UserId is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "UserId must be a positive integer.")]
        public int UserId { get; set; }

        /// <summary>
        /// Title of the report.
        /// </summary>
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Title must be between 1 and 255 characters.")]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed content of the report.
        /// </summary>
        [Required(ErrorMessage = "Content is required.")]
        [StringLength(1000, MinimumLength = 1, ErrorMessage = "Content must be between 1 and 1000 characters.")]
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// Date and time when the report was generated.
        /// </summary>
        [Required(ErrorMessage = "GeneratedDate is required.")]
        public DateTime GeneratedDate { get; set; }

        /// <summary>
        /// Navigation property for the user who generated the report.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public User User { get; set; } = null!;
    }
}