namespace BackendBiblioMate.DTOs
{
    /// <summary>
    /// Data Transfer Object returned when retrieving report information.
    /// Contains metadata and generated content of an analytical report.
    /// </summary>
    public class ReportReadDto
    {
        /// <summary>
        /// Gets or sets the unique identifier of the report.
        /// </summary>
        /// <example>8</example>
        public int ReportId { get; init; }

        /// <summary>
        /// Gets or sets the title of the report.
        /// </summary>
        /// <example>Monthly Usage Statistics</example>
        public string Title { get; init; } = string.Empty;

        /// <summary>
        /// Gets or sets the detailed content of the report.
        /// </summary>
        /// <remarks>
        /// This may include narrative sections, tables, or summary points generated by the system.
        /// </remarks>
        /// <example>The number of loans increased by 15% compared to the previous month...</example>
        public string Content { get; init; } = string.Empty;

        /// <summary>
        /// Gets or sets the date and time when the report was generated, in UTC.
        /// </summary>
        /// <example>2025-06-20T14:30:00Z</example>
        public DateTime GeneratedDate { get; init; }

        /// <summary>
        /// Gets or sets the identifier of the user who generated the report.
        /// </summary>
        /// <example>7</example>
        public int UserId { get; init; }

        /// <summary>
        /// Gets or sets the full name of the user who generated the report.
        /// </summary>
        /// <example>Jane Doe</example>
        public string UserName { get; init; } = string.Empty;
    }
}